
export const GET_ACCOUNT_LIST = "GET_ACCOUNT_LIST";
export const GET_ACCOUNT_DETAIL = "GET_ACCOUNT_DETAIL";
export const GET_ACCOUNT_PATIENT_LIST = "GET_ACCOUNT_PATIENT_LIST";
export const GET_ACCOUNT_DOCTOR_LIST = "GET_ACCOUNT_DOCTOR_LIST";
export const GET_DOCTOR_DEPARTMENT_DETAIL = "GET_DOCTOR_DEPARTMENT_DETAIL";
export const GET_DEPARTMENT_FOR_DOCTOR_FROM_ADMIN = "GET_DEPARTMENT_FOR_DOCTOR_FROM_ADMIN";
export const GET_DOCTOR_WITHOUT_DEPARTMENT = "GET_DOCTOR_WITHOUT_DEPARTMENT";
export const GET_DEPARTMENT = "GET_DEPARTMENT";
export const GET_SYMPTOM = "GET_SYMPTOM";
export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
